"""Add github_data jsonb column to repository

Revision ID: 14085b35e14d
Revises: a6479fd5f9b7
Create Date: 2026-01-31 10:02:10.226625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '14085b35e14d'
down_revision: Union[str, None] = 'a6479fd5f9b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repository', sa.Column('github_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('repository', 'latest_version',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('repository', 'latest_version',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.drop_column('repository', 'github_data')
    # ### end Alembic commands ###
