"""Update models to match PRD

Revision ID: a6479fd5f9b7
Revises: d6c79ecb8e65
Create Date: 2026-01-29 15:44:30.190207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a6479fd5f9b7'
down_revision: Union[str, None] = 'd6c79ecb8e65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repository', sa.Column('detected_platforms', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('repository', sa.Column('primary_category', sa.String(length=50), nullable=True))
    op.add_column('repository', sa.Column('total_downloads', sa.Integer(), nullable=True, server_default='0'))
    op.add_column('repository', sa.Column('latest_version', sa.String(length=100), nullable=True))
    op.add_column('repository', sa.Column('latest_release_date', sa.DateTime(), nullable=True))

    op.create_index(op.f('ix_recommendation_display_order'), 'recommendation', ['display_order'], unique=False)
    op.create_index(op.f('ix_recommendation_is_active'), 'recommendation', ['is_active'], unique=False)
    op.create_index(op.f('ix_recommendation_type'), 'recommendation', ['type'], unique=False)
    op.create_index(op.f('ix_release_is_latest'), 'release', ['is_latest'], unique=False)
    op.create_index(op.f('ix_release_published_at'), 'release', ['published_at'], unique=False)
    op.create_index(op.f('ix_release_repo_id'), 'release', ['repo_id'], unique=False)
    op.create_index(op.f('ix_release_tag_name'), 'release', ['tag_name'], unique=False)
    op.create_index(op.f('ix_releaseasset_file_type'), 'releaseasset', ['file_type'], unique=False)
    op.create_index(op.f('ix_releaseasset_name'), 'releaseasset', ['name'], unique=False)
    op.create_index(op.f('ix_releaseasset_platform'), 'releaseasset', ['platform'], unique=False)
    op.create_index(op.f('ix_releaseasset_release_id'), 'releaseasset', ['release_id'], unique=False)
    op.create_index(op.f('ix_repository_has_releases'), 'repository', ['has_releases'], unique=False)
    op.create_index(op.f('ix_repository_is_active'), 'repository', ['is_active'], unique=False)
    op.create_index(op.f('ix_repository_language'), 'repository', ['language'], unique=False)
    op.create_index(op.f('ix_repository_next_update_at'), 'repository', ['next_update_at'], unique=False)
    op.create_index(op.f('ix_repository_stars'), 'repository', ['stars'], unique=False)
    op.create_index(op.f('ix_repository_update_priority'), 'repository', ['update_priority'], unique=False)
    op.create_index(op.f('ix_searchhistory_created_at'), 'searchhistory', ['created_at'], unique=False)
    op.create_index(op.f('ix_searchhistory_query'), 'searchhistory', ['query'], unique=False)
    op.create_index(op.f('ix_searchhistory_user_id'), 'searchhistory', ['user_id'], unique=False)
    op.alter_column('systemconfig', 'value',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.drop_constraint('systemconfig_key_key', 'systemconfig', type_='unique')
    op.create_index(op.f('ix_systemconfig_key'), 'systemconfig', ['key'], unique=True)
    op.alter_column('user', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('user_id_seq'::regclass)"))
    op.create_index(op.f('ix_user_created_at'), 'user', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_status'), 'user', ['status'], unique=False)
    op.create_index(op.f('ix_userfavorite_created_at'), 'userfavorite', ['created_at'], unique=False)
    op.create_index(op.f('ix_userfavorite_repo_id'), 'userfavorite', ['repo_id'], unique=False)
    op.create_index(op.f('ix_userfavorite_user_id'), 'userfavorite', ['user_id'], unique=False)
    op.create_unique_constraint('user_repo_favorite_uc', 'userfavorite', ['user_id', 'repo_id'])
    op.create_index(op.f('ix_usersession_expires_at'), 'usersession', ['expires_at'], unique=False)
    op.create_index(op.f('ix_usersession_user_id'), 'usersession', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repository', 'latest_release_date')
    op.drop_column('repository', 'latest_version')
    op.drop_column('repository', 'total_downloads')
    op.drop_column('repository', 'primary_category')
    op.drop_column('repository', 'detected_platforms')
    
    op.drop_index(op.f('ix_usersession_user_id'), table_name='usersession')
    op.drop_index(op.f('ix_usersession_expires_at'), table_name='usersession')
    op.drop_constraint('user_repo_favorite_uc', 'userfavorite', type_='unique')
    op.drop_index(op.f('ix_userfavorite_user_id'), table_name='userfavorite')
    op.drop_index(op.f('ix_userfavorite_repo_id'), table_name='userfavorite')
    op.drop_index(op.f('ix_userfavorite_created_at'), table_name='userfavorite')
    op.drop_index(op.f('ix_user_status'), table_name='user')
    op.drop_index(op.f('ix_user_created_at'), table_name='user')
    op.alter_column('user', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('user_id_seq'::regclass)"))
    op.drop_index(op.f('ix_systemconfig_key'), table_name='systemconfig')
    op.create_unique_constraint('systemconfig_key_key', 'systemconfig', ['key'], postgresql_nulls_not_distinct=False)
    op.alter_column('systemconfig', 'value',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.drop_index(op.f('ix_searchhistory_user_id'), table_name='searchhistory')
    op.drop_index(op.f('ix_searchhistory_query'), table_name='searchhistory')
    op.drop_index(op.f('ix_searchhistory_created_at'), table_name='searchhistory')
    op.drop_index(op.f('ix_repository_update_priority'), table_name='repository')
    op.drop_index(op.f('ix_repository_stars'), table_name='repository')
    op.drop_index(op.f('ix_repository_next_update_at'), table_name='repository')
    op.drop_index(op.f('ix_repository_language'), table_name='repository')
    op.drop_index(op.f('ix_repository_is_active'), table_name='repository')
    op.drop_index(op.f('ix_repository_has_releases'), table_name='repository')
    op.drop_index(op.f('ix_releaseasset_release_id'), table_name='releaseasset')
    op.drop_index(op.f('ix_releaseasset_platform'), table_name='releaseasset')
    op.drop_index(op.f('ix_releaseasset_name'), table_name='releaseasset')
    op.drop_index(op.f('ix_releaseasset_file_type'), table_name='releaseasset')
    op.drop_index(op.f('ix_release_tag_name'), table_name='release')
    op.drop_index(op.f('ix_release_repo_id'), table_name='release')
    op.drop_index(op.f('ix_release_published_at'), table_name='release')
    op.drop_index(op.f('ix_release_is_latest'), table_name='release')
    op.drop_index(op.f('ix_recommendation_type'), table_name='recommendation')
    op.drop_index(op.f('ix_recommendation_is_active'), table_name='recommendation')
    op.drop_index(op.f('ix_recommendation_display_order'), table_name='recommendation')
    # ### end Alembic commands ###
