"""Initial migration

Revision ID: d6c79ecb8e65
Revises: 
Create Date: 2026-01-29 15:18:53.629741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd6c79ecb8e65'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommendation',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('repo_ids', postgresql.ARRAY(sa.BigInteger()), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('start_at', sa.DateTime(), nullable=True),
    sa.Column('end_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendation_id'), 'recommendation', ['id'], unique=False)
    op.create_table('repository',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('owner', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('homepage', sa.String(length=255), nullable=True),
    sa.Column('github_id', sa.BigInteger(), nullable=True),
    sa.Column('html_url', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=255), nullable=True),
    sa.Column('stars', sa.Integer(), nullable=True),
    sa.Column('forks', sa.Integer(), nullable=True),
    sa.Column('watchers', sa.Integer(), nullable=True),
    sa.Column('open_issues', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('topics', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('has_releases', sa.Boolean(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('update_priority', sa.SmallInteger(), nullable=True),
    sa.Column('next_update_at', sa.DateTime(), nullable=True),
    sa.Column('github_created_at', sa.DateTime(), nullable=True),
    sa.Column('github_updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('github_id')
    )
    op.create_index(op.f('ix_repository_category'), 'repository', ['category'], unique=False)
    op.create_index(op.f('ix_repository_full_name'), 'repository', ['full_name'], unique=True)
    op.create_index(op.f('ix_repository_id'), 'repository', ['id'], unique=False)
    op.create_table('systemconfig',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_index(op.f('ix_systemconfig_id'), 'systemconfig', ['id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=True),
    sa.Column('avatar_url', sa.String(length=255), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_phone'), 'user', ['phone'], unique=True)
    op.create_table('readmecache',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('repo_id', sa.BigInteger(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('html_content', sa.Text(), nullable=True),
    sa.Column('encoding', sa.String(length=20), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['repo_id'], ['repository.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repo_id')
    )
    op.create_index(op.f('ix_readmecache_id'), 'readmecache', ['id'], unique=False)
    op.create_table('release',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('repo_id', sa.BigInteger(), nullable=False),
    sa.Column('github_release_id', sa.BigInteger(), nullable=True),
    sa.Column('tag_name', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('is_prerelease', sa.Boolean(), nullable=True),
    sa.Column('is_draft', sa.Boolean(), nullable=True),
    sa.Column('is_latest', sa.Boolean(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['repo_id'], ['repository.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('github_release_id')
    )
    op.create_index(op.f('ix_release_id'), 'release', ['id'], unique=False)
    op.create_table('searchhistory',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('filters', sa.JSON(), nullable=True),
    sa.Column('result_count', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_searchhistory_id'), 'searchhistory', ['id'], unique=False)
    op.create_table('userfavorite',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('repo_id', sa.BigInteger(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['repo_id'], ['repository.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_userfavorite_id'), 'userfavorite', ['id'], unique=False)
    op.create_table('usersession',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('device_info', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usersession_id'), 'usersession', ['id'], unique=False)
    op.create_index(op.f('ix_usersession_token'), 'usersession', ['token'], unique=True)
    op.create_table('releaseasset',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('release_id', sa.BigInteger(), nullable=False),
    sa.Column('github_asset_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('size', sa.BigInteger(), nullable=True),
    sa.Column('browser_download_url', sa.Text(), nullable=False),
    sa.Column('download_count', sa.Integer(), nullable=True),
    sa.Column('platform', sa.String(length=50), nullable=True),
    sa.Column('file_type', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['release_id'], ['release.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('github_asset_id')
    )
    op.create_index(op.f('ix_releaseasset_id'), 'releaseasset', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_releaseasset_id'), table_name='releaseasset')
    op.drop_table('releaseasset')
    op.drop_index(op.f('ix_usersession_token'), table_name='usersession')
    op.drop_index(op.f('ix_usersession_id'), table_name='usersession')
    op.drop_table('usersession')
    op.drop_index(op.f('ix_userfavorite_id'), table_name='userfavorite')
    op.drop_table('userfavorite')
    op.drop_index(op.f('ix_searchhistory_id'), table_name='searchhistory')
    op.drop_table('searchhistory')
    op.drop_index(op.f('ix_release_id'), table_name='release')
    op.drop_table('release')
    op.drop_index(op.f('ix_readmecache_id'), table_name='readmecache')
    op.drop_table('readmecache')
    op.drop_index(op.f('ix_user_phone'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_systemconfig_id'), table_name='systemconfig')
    op.drop_table('systemconfig')
    op.drop_index(op.f('ix_repository_id'), table_name='repository')
    op.drop_index(op.f('ix_repository_full_name'), table_name='repository')
    op.drop_index(op.f('ix_repository_category'), table_name='repository')
    op.drop_table('repository')
    op.drop_index(op.f('ix_recommendation_id'), table_name='recommendation')
    op.drop_table('recommendation')
    # ### end Alembic commands ###
